-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpiceReminder/maintenance/db/sql/bs_reminder.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/bs_reminder (
  rem_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  rem_user_id INTEGER NOT NULL,
  rem_page_id INTEGER NOT NULL,
  rem_date DATETIME NOT NULL,
  rem_comment BLOB NOT NULL,
  rem_is_repeating SMALLINT DEFAULT 0 NOT NULL,
  rem_repeat_date_end VARCHAR(14) DEFAULT '' NOT NULL,
  rem_repeat_config BLOB NOT NULL,
  rem_type VARCHAR(255) DEFAULT '' NOT NULL
);

CREATE INDEX rem_user_id_idx ON /*_*/bs_reminder (rem_user_id);

CREATE INDEX rem_page_id_idx ON /*_*/bs_reminder (rem_page_id);

CREATE INDEX rem_user_page_idx ON /*_*/bs_reminder (rem_user_id, rem_page_id);

CREATE INDEX rem_date_idx ON /*_*/bs_reminder (rem_date);
