-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpiceReminder/maintenance/db/sql/bs_reminder.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/bs_reminder (
  rem_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  rem_user_id INT NOT NULL,
  rem_page_id INT NOT NULL,
  rem_date DATETIME NOT NULL,
  rem_comment VARBINARY(255) NOT NULL,
  rem_is_repeating TINYINT(1) DEFAULT 0 NOT NULL,
  rem_repeat_date_end VARCHAR(14) DEFAULT '' NOT NULL,
  rem_repeat_config BLOB NOT NULL,
  rem_type VARCHAR(255) DEFAULT '' NOT NULL,
  INDEX rem_user_id_idx (rem_user_id),
  INDEX rem_page_id_idx (rem_page_id),
  INDEX rem_user_page_idx (rem_user_id, rem_page_id),
  INDEX rem_date_idx (rem_date),
  PRIMARY KEY(rem_id)
) /*$wgDBTableOptions*/;
